LOCATION_MAPPING = {
    -- South Clock Town
    [0x061A00] = {"@Clock Town/Before Clock Town/Chest"},

    [0x000037] = {"@Clock Town/Spawn Area/Link's Inventory (Kokiri Sword)"},
    [0x056F0A] = {"@Clock Town/Clock Tower Platform/Freestanding HP"},
    [0x040068] = {"@Clock Town/Clock Tower/Happy Mask Salesman #1"},
    [0x000078] = {"@Clock Town/Clock Tower/Happy Mask Salesman #2"},
    [0x066F00] = {"@Clock Town/South Clock Town Corner/Chest"},
    [0x066F01] = {"@Clock Town/South Clock Town Tower/Chest (Final Day)"},
    [0x00004C] = {"@Clock Town/Clock Tower/Top of Clock Tower (Ocarina of Time)"},
    [0x040067] = {"@Clock Town/Clock Tower/Top of Clock Tower (Song of Time)"},
    [0x000097] = {"@Clock Town/South Clock Town Business Scrub/Moon's Tear Trade"},
    [0x0701F2] = {"@Clock Town/Clock Town Postbox/Interact with Postman's Hat equipped"},

    -- Laundry Pool
    [0x01007F] = {"@Clock Town/Stray Fairy (Clock Town)/Stray Fairy (Clock Town)"},
    [0x00008C] = {"@Clock Town/Laundry Pool/Musician (Night 1 - 2)"},
    [0x0000AB] = {"@Clock Town/Curiosity Shop Backroom/Kafei's Request (Day 2, 4:30 PM)"},
    [0x000080] = {"@Clock Town/Curiosity Shop Backroom/Curiosity Shop Salesman #1 (Final Day, 1 PM - 9 PM)"},
    [0x0000A1] = {"@Clock Town/Curiosity Shop Backroom/Curiosity Shop Salesman #2 (Final Day, 1 PM - 9 PM)"},

    -- East Clock Town
    [0x066C0A] = {"@Clock Town/Archery Roof/Chest"},
    [0x00008F] = {"@Clock Town/Mayor's Residence (10 AM - 10 PM)/Mayor's Wife"},
    [0x07026F] = {"@Clock Town/Mayor's Residence (10 AM - 10 PM)/Couple's Mask on Mayor"},
    [0x000023] = {"@Clock Town/Town Shooting Gallery (6 AM - 10 PM)/Score 40-49 Points"},
    [0x07011D] = {"@Clock Town/Town Shooting Gallery (6 AM - 10 PM)/Score Perfect 50 Points"},
    [0x0800B5] = {"@Clock Town/Honey and Darling (6 AM - 10 PM)/Win Any Day"},
    [0x0700B5] = {"@Clock Town/Honey and Darling (6 AM - 10 PM)/Win All Days"},
    [0x061705] = {"@Clock Town/Treasure Game (6 AM - 10 PM)/Chest (Human)"},
    [0x06172A] = {"@Clock Town/Treasure Game (6 AM - 10 PM)/Chest (Deku)"},
    [0x06170C] = {"@Clock Town/Treasure Game (6 AM - 10 PM)/Chest (Goron)"},
    [0x061704] = {"@Clock Town/Treasure Game (6 AM - 10 PM)/Chest (Zora)"},
    [0x062900] = {"@Clock Town/Bomber's Secret Hideout/Hidden Chest"},
    [0x000096] = {"@Termina Field/Astral Observatory/Moon's Tear"},
    [0x0000A0] = {"@Clock Town/Stock Pot Inn/Reservation (Day 1: 1 to 4 PM)"},
    [0x0000AA] = {"@Clock Town/Stock Pot Inn/Midnight Meeting (Night 1: 12 to 6 AM)"},
    [0x066100] = {"@Clock Town/Stock Pot Inn/Locked Room Chest"},
    [0x066101] = {"@Clock Town/Stock Pot Inn/Employee Room Chest (Final Night)"},
    [0x07027D] = {"@Clock Town/Stock Pot Inn/Midnight Toilet Hand"},
    [0x070243] = {"@Clock Town/Stock Pot Inn/Granny Story #1"},
    [0x080243] = {"@Clock Town/Stock Pot Inn/Granny Story #2"},
    [0x000085] = {"@Clock Town/Stock Pot Inn/Anju and Kafei (Final Night: 4:30 AM)"},
    [0x000083] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Milk Bar Show (Night 1 - 2)"},
    [0x00006F] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Priority Mail to Aroma (Final Night)"},
    [0x026392] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Milk Purchase"},
    [0x000091] = {"@Clock Town/Milk Bar (10 PM - 6 AM)/Chateau Romani Purchase"},

    -- North Clock Town
    [0x056E0A] = {"@Clock Town/North Clock Town - Tree/Tree Heart Piece"},
    [0x00008D] = {"@Clock Town/North Clock Town Save Old Lady/North Clock Town Save Old Lady (Night 1 - 12 AM)"},
    [0x000050] = {"@Clock Town/North Clock Town - Bombers/Hide-and-Seek"},
    [0x0801C9] = {"@Clock Town/Deku Playground/Win Any Day"},
    [0x0701C9] = {"@Clock Town/Deku Playground/Win All Days"},
    [0x07028C] = {"@Clock Town/Keaton/Keaton Quiz"},
    [0x030000] = {"@Clock Town/Clock Town Great Fairy/Great Fairy Reward"},
    [0x000086] = {"@Clock Town/Clock Town Great Fairy/Great Fairy Reward (Transformation Mask)"},
    [0x0000B4] = {"clock_town_map_purchase_1"},

    -- West Clock Town
    [0x0701EF] = {"@Clock Town/Swordsman School/Expert Course"},
    [0x07017D] = {"@Clock Town/Post Office/Postman Counting (Day 1: 3 PM - Midnight)"},
    [0x000084] = {"@Clock Town/Post Office/Priority Mail to Postman (Final Night)"},
    [0x07027B] = {"@Clock Town/Rosa Sisters/Rosa Sisters (Night 1 - 2)"},
    [0x000008] = {"@Clock Town/Clock Town Bank/Deposit 200 Rupees"},
    [0x080177] = {"@Clock Town/Clock Town Bank/Deposit 500 Rupees"},
    [0x070177] = {"@Clock Town/Clock Town Bank/Deposit 1000 Rupees"},
    [0x09001A] = {"@Clock Town/Bomb Shop/Item 1"},
    [0x090019] = {"@Clock Town/Bomb Shop/Item 2"},
    [0x090017] = {"@Clock Town/Bomb Shop/Item 3"},
    [0x090018] = {"@Clock Town/Bomb Shop/Item 3 (Stop Thief)"},
    [0x024234] = {"@Clock Town/Bomb Shop/Powder Keg Goron"},
    [0x09000A] = {"@Clock Town/Trading Post/Shop Item 1"},
    [0x090005] = {"@Clock Town/Trading Post/Shop Item 2"},
    [0x090006] = {"@Clock Town/Trading Post/Shop Item 3"},
    [0x090003] = {"@Clock Town/Trading Post/Shop Item 4"},
    [0x090007] = {"@Clock Town/Trading Post/Shop Item 5"},
    [0x090008] = {"@Clock Town/Trading Post/Shop Item 6"},
    [0x090009] = {"@Clock Town/Trading Post/Shop Item 7"},
    [0x090004] = {"@Clock Town/Trading Post/Shop Item 8"},
    [0x090012] = {"@Clock Town/Trading Post/Shop (Night) Item 1"},
    [0x09000E] = {"@Clock Town/Trading Post/Shop (Night) Item 2"},
    [0x090011] = {"@Clock Town/Trading Post/Shop (Night) Item 3"},
    [0x09000B] = {"@Clock Town/Trading Post/Shop (Night) Item 4"},
    [0x090010] = {"@Clock Town/Trading Post/Shop (Night) Item 5"},
    [0x09000C] = {"@Clock Town/Trading Post/Shop (Night) Item 6"},
    [0x09000F] = {"@Clock Town/Trading Post/Shop (Night) Item 7"},
    [0x09000D] = {"@Clock Town/Trading Post/Shop (Night) Item 8"},
    [0x090013] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Night 3 (Stop Thief)"},
    [0x090015] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Night 3 Thief Stolen Item"},
    [0x07C402] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Blue Rupee Trade (Half Milk, Magic Mushroom)"},
    [0x07C404] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Red Rupee Trade (Fish, Bug, Fairy, Milk, Potions, Water, Zora Egg)"},
    [0x07C405] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Purple Rupee Trade (Poe)"},
    [0x07C407] = {"@Clock Town/Curiosity Shop (10 PM - 6 AM)/Gold Rupee Trade (Big Poe, Chateau, Gold Dust)"},
    [0x080239] = {"@Clock Town/West Clock Town Lottery/Win Any Day"},

    -- Termina Field
    [0x062D02] = {"@Termina Field/Termina Field Stump/Stump Chest"},
    [0x062D01] = {"@Termina Field/Termina Field Grass Chest/Grass Chest"},
    [0x062D00] = {"@Termina Field/Termina Field Pond/Underwater Chest"},
    [0x06071F] = {"@Termina Field/Grass Grotto/Chest"},
    [0x060704] = {"@Termina Field/Peahat Grotto/Defeat Peahat (Daytime Only)"},
    [0x060700] = {"@Termina Field/Dodongo Grotto/Dodongo Chest"},
    [0x06071A] = {"@Termina Field/Pillar Grotto/Chest"},
    [0x000089] = {"@Termina Field/Kamaro/Healing Kamaro (Midnight - 6 AM)"},
    [0x050702] = {"@Termina Field/Bio Baba Grotto/Right Beehive Heart Piece"},
    [0x0700EF] = {"@Termina Field/Termina Gossip Stones/Reward"},
    [0x07024C] = {"@Termina Field/Business Scrub Grotto/Purchase Heart Piece"},
    [0xBEEF14] = {"@Termina Field/Hollowed Log Bombable Grotto/Left Cow"},
    [0xBEEF13] = {"@Termina Field/Hollowed Log Bombable Grotto/Right Cow"},

    -- Milk Road/Romani Ranch
    [0x0000B7] = {"romani_ranch_map_purchase_1"},
    [0x0000B8] = {"great_bay_map_purchase_1"},
    [0x000081] = {"@Romani Ranch/Gorman Track/Race"},
    [0x006792] = {"@Romani Ranch/Gorman Track/Purchase"},
    [0x00007F] = {"@Romani Ranch/Cucco Shack/Baby Cuccos March"},
    [0x064100] = {"@Romani Ranch/Mamamu Yan's Doggy Racetrack/Rooftop Chest"},
    [0x070117] = {"@Romani Ranch/Mamamu Yan's Doggy Racetrack/Doggy Race"},
    [0xBEEF10] = {"@Romani Ranch/Romani Ranch Barn/Free Cow"},
    [0xBEEF11] = {"@Romani Ranch/Romani Ranch Barn/Stables Front Cow"},
    [0xBEEF12] = {"@Romani Ranch/Romani Ranch Barn/Stables Back Cow"},
    [0x0000A5] = {"@Romani Ranch/Romani Ranch Outside/Romani Game"},
    [0x000060] = {"@Romani Ranch/Romani Ranch Outside/Aliens"},
    [0x000082] = {"@Romani Ranch/Romani Ranch Outside/Helping Cremia"},

    -- Southern Swamp
    [0x054001] = {"@Southern Swamp/Road to Swamp/Tree HP"},
    [0x06071E] = {"@Southern Swamp/Road to Swamp Grotto/Chest"},
    [0x000024] = {"@Southern Swamp/Swamp Shooting Gallery/Score 2120 Points"},
    [0x08011D] = {"@Southern Swamp/Swamp Shooting Gallery/Score 2180 Points"},
    [0x0000B5] = {"@Southern Swamp/Tingle Southern Swamp/Woodfall Map Purchase"},
    [0x000098] = {"@Southern Swamp/Swamp Business Scrub/Deed Trade (as Human)"},
    [0x090135] = {"@Southern Swamp/Swamp Business Scrub/Deku Scrub Purchase"},
    [0x05451E] = {"@Southern Swamp/Swamp Business Scrub/Freestanding Heart Piece"},
    [0x000059] = {"@Southern Swamp/Kotake Item/Kotake Item"},
    [0x090002] = {"@Southern Swamp/Witch Shop/Item 1"},
    [0x090001] = {"@Southern Swamp/Witch Shop/Item 2"},
    [0x090000] = {"@Southern Swamp/Witch Shop/Item 3"},
    [0x06071C] = {"@Southern Swamp/Woods of Mystery Day 2 Grotto/Chest"},
    [0x000043] = {"@Southern Swamp/Swamp Tourist Center/Healing Koume"},
    [0x06071D] = {"@Southern Swamp/Southern Swamp Grotto/Chest"},
    [0x04006A] = {"@Southern Swamp/Southern Swamp Song Tablet/Song of Soaring Tablet"},
    [0x052B1E] = {"@Southern Swamp/Left Inner Palace Garden/Heart Piece"},
    [0x060705] = {"@Southern Swamp/Deku Palace Bean Grotto/Chest"},
    [0x0800A5] = {"@Southern Swamp/Deku Palace Bean Grotto/Bean Seller"},
    [0x040061] = {"@Southern Swamp/Deku King's Chamber/Monkey Song"},
    [0x00008E] = {"@Southern Swamp/Deku Shrine/Butler Race"},
    [0x064602] = {"@Southern Swamp/Woodfall/Owl Statue Chest"},
    [0x064601] = {"@Southern Swamp/Woodfall/Bridge Chest"},
    [0x064600] = {"@Southern Swamp/Woodfall/Entrance Chest"},
    [0x030001] = {"@Southern Swamp/Woodfall/Great Fairy Reward"},
    [0x070168] = {"@Southern Swamp/Swamp Tourist Center/Boat Archery"},
    [0x0701C5] = {"@Southern Swamp/Swamp Tourist Center/Winning Picture (Tingle or Deku King)"},
    [0x071C54] = {"@Southern Swamp/Swamp Tourist Center/Good Picture (Big Octo)"},
    [0x071C52] = {"@Southern Swamp/Swamp Tourist Center/Okay Picture (Anything else)"},

    -- Swamp Spider House
    [0x06271E] = {"@Dungeons/Swamp Spider House/First Room Pot Near Entrance Token"},
    [0x062708] = {"@Dungeons/Swamp Spider House/First Room Crawling In Water Token"},
    [0x06270F] = {"@Dungeons/Swamp Spider House/First Room Crawling Right Column Token"},
    [0x062713] = {"@Dungeons/Swamp Spider House/First Room Crawling Left Column Token"},
    [0x062700] = {"@Dungeons/Swamp Spider House/First Room Against Far Wall Token"},
    [0x062709] = {"@Dungeons/Swamp Spider House/First Room Left Bugpatch Token"},
    [0x06270C] = {"@Dungeons/Swamp Spider House/First Room Right Bugpatch Token"},
    [0x06270B] = {"@Dungeons/Swamp Spider House/First Room Upper Right Bugpatch Token"},
    [0x06270A] = {"@Dungeons/Swamp Spider House/Monument Room Left Crate Token"},
    [0x06271B] = {"@Dungeons/Swamp Spider House/Monument Room Right Crate Token"},
    [0x06270D] = {"@Dungeons/Swamp Spider House/Monument Room Crawling Wall Token"},
    [0x06270E] = {"@Dungeons/Swamp Spider House/Monument Room Crawling On Monument Token"},
    [0x062702] = {"@Dungeons/Swamp Spider House/Monument Room Behind Torch Token"},
    [0x062717] = {"@Dungeons/Swamp Spider House/Pottery Room Beehive #1 Token"},
    [0x06271C] = {"@Dungeons/Swamp Spider House/Pottery Room Beehive #2 Token"},
    [0x062705] = {"@Dungeons/Swamp Spider House/Pottery Room Small Pot Token"},
    [0x062710] = {"@Dungeons/Swamp Spider House/Pottery Room Left Large Pot Token"},
    [0x062711] = {"@Dungeons/Swamp Spider House/Pottery Room Right Large Pot Token"},
    [0x062714] = {"@Dungeons/Swamp Spider House/Pottery Room Behind Vines Token"},
    [0x062716] = {"@Dungeons/Swamp Spider House/Pottery Room Upper Wall Token"},
    [0x062719] = {"@Dungeons/Swamp Spider House/Golden Room Crawling Left Wall Token"},
    [0x062704] = {"@Dungeons/Swamp Spider House/Golden Room Crawling Right Column Token"},
    [0x062701] = {"@Dungeons/Swamp Spider House/Golden Room Against Far Wall Token"},
    [0x062712] = {"@Dungeons/Swamp Spider House/Golden Room Beehive Token"},
    [0x062707] = {"@Dungeons/Swamp Spider House/Tree Room Tall Grass #1 Token"},
    [0x062706] = {"@Dungeons/Swamp Spider House/Tree Room Tall Grass #2 Token"},
    [0x062715] = {"@Dungeons/Swamp Spider House/Tree Room Tree #1 Token"},
    [0x062718] = {"@Dungeons/Swamp Spider House/Tree Room Tree #2 Token"},
    [0x06271D] = {"@Dungeons/Swamp Spider House/Tree Room Tree #3 Token"},
    [0x06271A] = {"@Dungeons/Swamp Spider House/Tree Room Beehive Token"},
    [0x00008A] = {"@Dungeons/Swamp Spider House/Swamp Spider House Reward"},

    -- Woodfall Temple
    [0x061B18] = {"@Dungeons/Woodfall Temple/Entrance Chest SF"},
    [0x061B01] = {"@Dungeons/Woodfall Temple/Ledge Chest"},
    [0x061B1D] = {"@Dungeons/Woodfall Temple/Turtle Chestt"},
    [0x061B1C] = {"@Dungeons/Woodfall Temple/Dragonfly Chest"},
    [0x061B19] = {"@Dungeons/Woodfall Temple/Dark Room Chest SF"},
    [0x061B17] = {"@Dungeons/Woodfall Temple/Switch Chest SF"},
    [0x061B1B] = {"@Dungeons/Woodfall Temple/Dinolfos Chest"},
    [0x061B1E] = {"@Dungeons/Woodfall Temple/Gekko Chest"},
    [0x011B2B] = {"@Dungeons/Woodfall Temple/Entrance Freestanding SF"},
    [0x011B2E] = {"@Dungeons/Woodfall Temple/Deku Baba SF"},
    [0x011B1C] = {"@Dungeons/Woodfall Temple/Pot SF"},
    [0x011B1E] = {"@Dungeons/Woodfall Temple/Platform Hive SF"},
    [0x011B30] = {"@Dungeons/Woodfall Temple/Main Room Bubble SF"},
    [0x011B31] = {"@Dungeons/Woodfall Temple/Skulltula SF"},
    [0x011B2F] = {"@Dungeons/Woodfall Temple/Bridge Room Bubble SF"},
    [0x011B1D] = {"@Dungeons/Woodfall Temple/Bridge Room Hive SF"},
    [0x011B2A] = {"@Dungeons/Woodfall Temple/Pre-Boss Lower Right Bubble SF"},
    [0x011B32] = {"@Dungeons/Woodfall Temple/Pre-Boss Upper Right Bubble SF"},
    [0x011B2C] = {"@Dungeons/Woodfall Temple/Pre-Boss Upper Left Bubble SF"},
    [0x011B2D] = {"@Dungeons/Woodfall Temple/Pre-Boss Pillar Bubble SF"},
    [0x051F00] = {"@Dungeons/Woodfall Temple/Heart Container"},
    [0x000055] = {"@Dungeons/Woodfall Temple/Odolwa's Remains"},

    -- Snowhead
    [0x065A00] = {"@Snowhead/Mountain Village/Spring Waterfall Chest"},
    [0x06071B] = {"@Snowhead/Mountain Village/Spring Ramp Grotto"},
    [0x000079] = {"@Snowhead/Darmani Graveyard/Healing Darmani"},
    [0x000088] = {"@Snowhead/Hungry Goron/Hungry Goron"},
    [0x070022] = {"@Snowhead/Mountain Village/Spring Frog Choir HP"},
    [0x000038] = {"@Snowhead/Mountain Village Smithy/Upgrade"},
    [0x000039] = {"@Snowhead/Mountain Village Smithy/Gold Dust Upgrade"},
    [0x0000B6] = {"snowhead_map_purchase_1"},
    [0x065E00] = {"@Snowhead/Twin Islands/Spring Underwater Cave Chest"},
    [0x065E06] = {"@Snowhead/Twin Islands/Spring Underwater Ramp Chest"},
    [0x060719] = {"@Snowhead/Twin Islands Ramp/Ramp Grotto Chest"},
    [0x0001AD] = {"@Snowhead/Twin Islands/Goron Elder Request"},
    [0x060702] = {"@Snowhead/Twin Islands Hot Spring Water Grotto/Chest"},
    [0x00006A] = {"@Snowhead/Goron Racetrack/Race Prize"},
    [0x060701] = {"@Snowhead/Lens Cave/Center Chest"},
    [0x060703] = {"@Snowhead/Lens Cave/Invisible Chest"},
    [0x060706] = {"@Snowhead/Lens Cave/Rock Chest"},
    [0x0000AD] = {"@Snowhead/Goron Shrine/Baby Goron Lullaby"},
    [0x09001E] = {"@Snowhead/Goron Shrine/Shop Item 1"},
    [0x09001F] = {"@Snowhead/Goron Shrine/Shop Item 2"},
    [0x090020] = {"@Snowhead/Goron Shrine/Shop Item 3"},
    [0x090021] = {"@Snowhead/Goron Shrine/Shop (Spring) Item 1"},
    [0x090022] = {"@Snowhead/Goron Shrine/Shop (Spring) Item 2"},
    [0x090023] = {"@Snowhead/Goron Shrine/Shop (Spring) Item 3"},
    [0x09011D] = {"@Snowhead/Goron Village/Scrub Purchase"},
    [0x000099] = {"@Snowhead/Goron Village/Deed Trade (as Deku)"},
    [0x054D1E] = {"@Snowhead/Goron Village/Freestanding Heart Piece"},
    [0x000034] = {"@Snowhead/Keg Goron/Powder Keg Goron Reward"},
    --[0x05481E] = {"@Snowhead/Goron Village/Freestanding Heart Piece (Spring)"},
    [0x060713] = {"@Snowhead/Path to Snowhead/Grotto Chest"},
    [0x055B08] = {"@Snowhead/Path to Snowhead/Scarecrow Pillar HP"},
    [0x030002] = {"@Snowhead/Snowhead/Snowhead Great Fairy Reward"},

    -- Snowhead Temple
    [0x062101] = {"@Dungeons/Snowhead Temple/Bridge Room Freezard Chest"},
    [0x01212F] = {"@Dungeons/Snowhead Temple/Bridge Room Under Platform Bubble SF"},
    [0x012130] = {"@Dungeons/Snowhead Temple/Bridge Room Pillar Bubble SF"},
    [0x06211C] = {"@Dungeons/Snowhead Temple/Frozen Block Chest"},
    [0x062119] = {"@Dungeons/Snowhead Temple/Frozen Block Upper Chest SF"},
    [0x01211E] = {"@Dungeons/Snowhead Temple/Bombable Stairs Crate SF"},
    [0x062115] = {"@Dungeons/Snowhead Temple/Stacked Block Upper Chest SF"},
    [0x062103] = {"@Dungeons/Snowhead Temple/Behind Stacked Block Chest"},
    [0x062118] = {"@Dungeons/Snowhead Temple/Freezard Torch Room Chest SF"},
    [0x062114] = {"@Dungeons/Snowhead Temple/Basement Switch Chest SF"},
    [0x062117] = {"@Dungeons/Snowhead Temple/Main Room Wall Chest SF"},
    [0x06211D] = {"@Dungeons/Snowhead Temple/Elevator Room Lower Chest"},
    [0x062113] = {"@Dungeons/Snowhead Temple/Elevator Room Invisible Platform Chest SF"},
    [0x012132] = {"@Dungeons/Snowhead Temple/Elevator Freestanding SF"},
    [0x062104] = {"@Dungeons/Snowhead Temple/Icicle Room Snowball Chest"},
    [0x062116] = {"@Dungeons/Snowhead Temple/Icicle Room Hidden Chest SF"},
    [0x01212C] = {"@Dungeons/Snowhead Temple/Timed Switch Room Bubble SF"},
    [0x06211B] = {"@Dungeons/Snowhead Temple/Lower Wizzrobe Chest"},
    [0x01212B] = {"@Dungeons/Snowhead Temple/Snowmen Bubble SF"},
    [0x012131] = {"@Dungeons/Snowhead Temple/Dinolfos Room First SF"},
    [0x01212D] = {"@Dungeons/Snowhead Temple/Dinolfos Room Second SF"},
    [0x06211E] = {"@Dungeons/Snowhead Temple/Upper Wizzrobe Chest"},
    [0x054400] = {"@Dungeons/Snowhead Temple/Heart Container"},
    [0x000056] = {"@Dungeons/Snowhead Temple/Goht's Remains"},

    -- Great Bay Coast
    [0x00007A] = {"@Great Bay/Great Bay Coast Beach/Healing Zora"},
    [0x060717] = {"@Great Bay/Fisherman's Hut/Fisherman's Grotto Chest"},
    [0x0000AC] = {"@Great Bay/Research Lab/Baby Zora Song"},
    [0x0701D9] = {"@Great Bay/Research Lab/Feeding Lab Fish"},
    [0xBEEF16] = {"@Great Bay/Great Bay CoastRock Wall/Cow Grotto Left Cow"},
    [0xBEEF15] = {"@Great Bay/Great Bay CoastRock Wall/Cow Grotto Right Cow"},
    [0x053705] = {"@Great Bay/Great Bay CoastRock Wall/Scarecrow Ledge Heart Piece"},
    [0x070292] = {"@Great Bay/Fisherman Island/Fisherman Game"},

    -- Zora Cape
    [0x053807] = {"@Great Bay/Like Like Pool/Underwater Heart Piece"},
    [0x063800] = {"@Great Bay/Underwater Chest/Chest"},
    [0x072806] = {"@Great Bay/Zora Pot Game/Game Reward"},
    [0x063801] = {"@Great Bay/Deku Flower Chest/Chest"},
    [0x063802] = {"@Great Bay/Scarecrow Chest/Chest"},
    [0x060715] = {"@Great Bay/Zora Cape Grotto/Chest"},
    [0x030003] = {"@Great Bay/Great Bay Great Fairy Cave/Great Fairy Reward"},
    [0x09018D] = {"@Great Bay/Waterfall Rapids/Beaver Bros. Race 1"},
    [0x07018D] = {"@Great Bay/Waterfall Rapids/Beaver Bros. Race 2"},

    -- Zora Hall
    [0x09001B] = {"@Great Bay/Zora Hall/Shop 1"},
    [0x09001C] = {"@Great Bay/Zora Hall/Shop 2"},
    [0x09001D] = {"@Great Bay/Zora Hall/Shop 3"},
    [0x09015C] = {"@Great Bay/Zora Hall/Deku Scrub Purchase"},
    [0x00009A] = {"@Great Bay/Zora Hall/Deed Trade (as Goron)"},
    [0x054C1E] = {"@Great Bay/Zora Hall/Scrub Trade Freestanding HP"},
    [0x070241] = {"@Great Bay/Zora Hall/Evan's Song"},
    [0x072802] = {"@Great Bay/Zora Hall/Torches Reward"},
    [0x082284] = {"@Great Bay/Zora Hall/Good Picture of Lulu"},
    [0x082282] = {"@Great Bay/Zora Hall/Bad Picture of Lulu"},

    -- Pinnacle Rock
    [0x070205] = {"@Great Bay/Pinnacle Rock/Seahorse Heart Piece"},
    [0x062502] = {"@Great Bay/Pinnacle Rock/Upper Eel Chest"},
    [0x062501] = {"@Great Bay/Pinnacle Rock/Lower Eel Chest"},

    -- Pirates' Fortress
    [0x063B00] = {"@Dungeons/Pirates' Fortress Moat/Underwater Log Chest"},
    [0x063B01] = {"@Dungeons/Pirates' Fortress Moat/Underwater Near Entrance Chest"},
    [0x063B02] = {"@Dungeons/Pirates' Fortress Moat/Underwater Corner Chest"},
    [0x05230C] = {"@Dungeons/Pirates' Fortress Sewers/Cage HP"},
    [0x062301] = {"@Dungeons/Pirates' Fortress Sewers/Maze Chest"},
    [0x062304] = {"@Dungeons/Pirates' Fortress Sewers/Underwater Lower Chest"},
    [0x062306] = {"@Dungeons/Pirates' Fortress Sewers/Underwater Upper Chest"},
    [0x062300] = {"@Dungeons/Pirates' Fortress/Tank Chest"},
    [0x062303] = {"@Dungeons/Pirates' Fortress/Guarded Chest"},
    [0x061400] = {"@Dungeons/Pirates' Fortress/Hub Lower Chest"},
    [0x061401] = {"@Dungeons/Pirates' Fortress/Hub Upper Chest"},
    [0x062302] = {"@Dungeons/Pirates' Fortress/Leader's Room Chest"},

    -- Ocean Spider House
    [0x06280C] = {"@Dungeons/Ocean Spider House/Ramp Upper Token"},
    [0x06280D] = {"@Dungeons/Ocean Spider House/Ramp Lower Token"},
    [0x06280F] = {"@Dungeons/Ocean Spider House/Lobby Ceiling Token"},
    [0x062806] = {"@Dungeons/Ocean Spider House/First Room Rafter Token"},
    [0x062818] = {"@Dungeons/Ocean Spider House/First Room Open Pot #1 Token"},
    [0x062817] = {"@Dungeons/Ocean Spider House/First Room Open Pot #2 Token"},
    [0x06281D] = {"@Dungeons/Ocean Spider House/First Room Wall Token"},
    [0x062804] = {"@Dungeons/Ocean Spider House/Library Top Bookcase Token"},
    [0x06281C] = {"@Dungeons/Ocean Spider House/Library Passage Behind Bookcase Front Token"},
    [0x062815] = {"@Dungeons/Ocean Spider House/Library Passage Behind Bookcase Rear Token"},
    [0x062814] = {"@Dungeons/Ocean Spider House/Library Painting #1 Token"},
    [0x062802] = {"@Dungeons/Ocean Spider House/Library Painting #2 Token"},
    [0x062808] = {"@Dungeons/Ocean Spider House/Library Rafter Token"},
    [0x062803] = {"@Dungeons/Ocean Spider House/Library Bookshelf Hole Token"},
    [0x062805] = {"@Dungeons/Ocean Spider House/First Room Downstairs Rafter Token"},
    [0x06281B] = {"@Dungeons/Ocean Spider House/First Room Downstairs Open Pot Token"},
    [0x06281E] = {"@Dungeons/Ocean Spider House/First Room Downstairs Behind Staircase Token"},
    [0x06280B] = {"@Dungeons/Ocean Spider House/First Room Downstairs Breakable Pot Token"},
    [0x06280E] = {"@Dungeons/Ocean Spider House/First Room Downstairs Wall Token"},
    [0x062819] = {"@Dungeons/Ocean Spider House/Dining Room Open Pot Token"},
    [0x062813] = {"@Dungeons/Ocean Spider House/Dining Room Painting Token"},
    [0x062807] = {"@Dungeons/Ocean Spider House/Dining Room Ceiling Token"},
    [0x062810] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #1 Token"},
    [0x062811] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #2 Token"},
    [0x062812] = {"@Dungeons/Ocean Spider House/Dining Room Chandelier #3 Token"},
    [0x062809] = {"@Dungeons/Ocean Spider House/Storage Room Web Token"},
    [0x062801] = {"@Dungeons/Ocean Spider House/Storage Room North Wall Token"},
    [0x062816] = {"@Dungeons/Ocean Spider House/Storage Room Crate Token"},
    [0x06280A] = {"@Dungeons/Ocean Spider House/Storage Room Hidden Hole Token"},
    [0x06281A] = {"@Dungeons/Ocean Spider House/Storage Room Ceiling Pot Token"},
    [0x062800] = {"@Dungeons/Ocean Spider House/Coloured Mask Sequence HP"},
    [0x000009] = {"@Dungeons/Ocean Spider House/Ocean Spider House Reward"},

    -- Great Bay Temple
    [0x064918] = {"@Dungeons/Great Bay Temple/Entrance Torches Chest SF"},
    [0x014932] = {"@Dungeons/Great Bay Temple/Waterwheel Room Skulltula SF"},
    [0x014930] = {"@Dungeons/Great Bay Temple/Waterwheel Room Bubble SF"},
    [0x01491C] = {"@Dungeons/Great Bay Temple/Blender Room Barrel SF"},
    [0x01491B] = {"@Dungeons/Great Bay Temple/Blender Pot SF"},
    [0x06491D] = {"@Dungeons/Great Bay Temple/Before Red Valve Room Chest"},
    [0x01491E] = {"@Dungeons/Great Bay Temple/Before Red Valve Room Pot SF"},
    [0x064919] = {"@Dungeons/Great Bay Temple/Bio-Baba Hall Chest SF"},
    [0x06491C] = {"@Dungeons/Great Bay Temple/Caged Chest Room Upper Chest"},
    [0x064901] = {"@Dungeons/Great Bay Temple/Caged Chest Room Underwater Chest"},
    [0x06491E] = {"@Dungeons/Great Bay Temple/Mad Jellied Gekko Chest"},
    [0x01491D] = {"@Dungeons/Great Bay Temple/Caged Chest Room Pot SF"},
    [0x06491B] = {"@Dungeons/Great Bay Temple/Behind Locked Door Chest"},
    [0x064915] = {"@Dungeons/Great Bay Temple/Room Behind Waterfall Ceiling Chest SF"},
    [0x064914] = {"@Dungeons/Great Bay Temple/Freezable Waterwheel Upper Chest SF"},
    [0x064917] = {"@Dungeons/Great Bay Temple/Freezable Waterwheel Lower Chest SF"},
    [0x01491A] = {"@Dungeons/Great Bay Temple/Seesaw Room Underwater Barrel SF"},
    [0x064916] = {"@Dungeons/Great Bay Temple/Seesaw Room Chest SF"},
    [0x014931] = {"@Dungeons/Great Bay Temple/Pre-Boss Room Platform Bubble SF"},
    [0x01492F] = {"@Dungeons/Great Bay Temple/Pre-Boss Room Tunnel Bubble SF"},
    [0x055F00] = {"@Dungeons/Great Bay Temple/Heart Container"},
    [0x000057] = {"@Dungeons/Great Bay Temple/Gyorg's Remains"},

    -- Road to Ikana
    [0x065300] = {"@Ikana/Road to Ikana Pillar Chest/Chest"},
    [0x060716] = {"@Ikana/Road to Ikana Rock Grotto/Chest"},
    [0x00008B] = {"@Ikana/Road to Ikana Stone Soldier/Stone Soldier"},

    -- Graveyard
    [0x060718] = {"@Ikana/Upper Graveyard/Bombable Grotto Chest"},
    [0x060C03] = {"@Ikana/Lower Graveyard/Day 1 Bats Chest"},
    [0x0000A2] = {"@Ikana/Lower Graveyard/Day 1 Iron Knuckle Song"},
    [0x060C00] = {"@Ikana/Lower Graveyard/Day 2 Iron Knuckle Chest"},
    [0x0043CA] = {"@Ikana/Lower Graveyard/Day 2 Dampe Bats"},
    [0x063000] = {"@Ikana/Lower Graveyard/Day 3 Dampe Big Poe Chest"},
    [0x064300] = {"@Ikana/Upper Graveyard/Captain Keeta Chest"},

    -- Secret Shrine
    [0x066000] = {"@Dungeons/Secret Shrine/Dinolfos Chest"},
    [0x066001] = {"@Dungeons/Secret Shrine/Wizzrobe Chest"},
    [0x066002] = {"@Dungeons/Secret Shrine/Wart Chest"},
    [0x066003] = {"@Dungeons/Secret Shrine/Garo Master Chest"},
    [0x06600A] = {"@Dungeons/Secret Shrine/Completion Chest"},

    -- Ikana Canyon
    [0x060714] = {"@Ikana/Near Secret Shrine Entrance/Grotto Chest"},
    [0x001307] = {"@Ikana/Near Thief's Hideout Entrance/Deed Trade (as Zora)"},
    [0x09015D] = {"@Ikana/Near Thief's Hideout Entrance/Scrub Purchase"},
    [0x05131E] = {"@Ikana/Near Thief's Hideout Entrance/Scrub Trade Freestanding HP"},
    [0x0000B9] = {"stone_tower_map_purchase_1"},
    [0x000087] = {"@Ikana/Music Box/Healing Pamela's Father"},
    [0x0701DE] = {"@Ikana/Spirit House/Poe Sisters"},
    [0x030004] = {"@Ikana/Great Fairy House/Great Fairy Reward"},

    -- Beneath the Well
    [0xBEEF17] = {"@Dungeons/Beneath the Well/Cow"},
    [0x064B02] = {"@Dungeons/Beneath the Well/Invisible Chest"},
    [0x064B01] = {"@Dungeons/Beneath the Well/Rightside Torch Chest"},
    [0x064B1B] = {"@Dungeons/Beneath the Well/Final Chest"},

    -- Ikana Castle
    [0x051D0A] = {"@Dungeons/Ikana Castle/Pillar Freestanding HP"},
    [0x040064] = {"@Dungeons/Ikana Castle/King Song"},

    -- Inverted Stone Tower
    [0x06591F] = {"@Ikana/Inverted Stone Tower/Left Chest"},
    [0x06591E] = {"@Ikana/Inverted Stone Tower/Middle Chest"},
    [0x06591D] = {"@Ikana/Inverted Stone Tower/Right Chest"},

    -- Stone Tower Temple
    [0x061616] = {"@Dungeons/Stone Tower Temple/Entrance Room Eye Switch Chest"},
    [0x061612] = {"@Dungeons/Stone Tower Temple/Entrance Room Lower Chest"},
    [0x06161D] = {"@Dungeons/Stone Tower Temple/Armos Room Back Chest"},
    [0x061615] = {"@Dungeons/Stone Tower Temple/Armos Room Upper Chest"},
    [0x061602] = {"@Dungeons/Stone Tower Temple/Armos Room Lava Chest"},
    [0x061618] = {"@Dungeons/Stone Tower Temple/Eyegore Room Switch Chest"},
    [0x061601] = {"@Dungeons/Stone Tower Temple/Eyegore Room Dexi Hand Ledge Chest"},
    [0x061617] = {"@Dungeons/Stone Tower Temple/Eastern Water Room Underwater Chest"},
    [0x06161C] = {"@Dungeons/Stone Tower Temple/Eastern Water Room Sun Block Chest"},
    [0x06160B] = {"@Dungeons/Stone Tower Temple/Mirror Room Sun Block Chest"},
    [0x06160F] = {"@Dungeons/Stone Tower Temple/Mirror Room Sun Face Chest"},
    [0x061619] = {"@Dungeons/Stone Tower Temple/Air Gust Room Side Chest"},
    [0x06160D] = {"@Dungeons/Stone Tower Temple/Air Gust Room Goron Switch Chest"},
    [0x06161B] = {"@Dungeons/Stone Tower Temple/Garo Master Chest"},
    [0x061614] = {"@Dungeons/Stone Tower Temple/After Garo Upside Down Chest"},
    [0x06160C] = {"@Dungeons/Stone Tower Temple/Eyegore Chest"},

    -- Inverted Stone Tower Temple
    [0x061810] = {"@Dungeons/Inverted Stone Tower Temple/Entrance Room Sun Face Chest"},
    [0x06180E] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Fire Chest"},
    [0x061813] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Frozen Switch Chest"},
    [0x061804] = {"@Dungeons/Inverted Stone Tower Temple/Eastern Air Gust Room Switch Chest"},
    [0x061811] = {"@Dungeons/Inverted Stone Tower Temple/Wizzrobe Chest"},
    [0x061805] = {"@Dungeons/Inverted Stone Tower Temple/Death Armos Maze Chest"},
    [0x06181E] = {"@Dungeons/Inverted Stone Tower Temple/Gomess Chest"},
    [0x06181A] = {"@Dungeons/Inverted Stone Tower Temple/Eyegore Chest"},
    [0x053600] = {"@Dungeons/Inverted Stone Tower Temple/Heart Container"},
    [0x000058] = {"@Dungeons/Inverted Stone Tower Temple/Twinmold's Remains"},

    -- Moon
    [0x052A01] = {"@Inside the Moon/Deku Trial/Heart Piece"},
    [0x053F01] = {"@Inside the Moon/Goron Trial/Heart Piece"},
    [0x054701] = {"@Inside the Moon/Zora Trial/Heart Piece"},
    [0x066601] = {"@Inside the Moon/Link Trial/Garo Master Chest"},
    [0x066602] = {"@Inside the Moon/Link Trial/Iron Knuckle Chest"},
    [0x056601] = {"@Inside the Moon/Link Trial/Heart Piece"},
    [0x00007B] = {"@Inside the Moon/The Moon/Trade All Masks"},

    -- Any Boss
    [0x040065] = {"oath_wft"}
}