CURRENT_ROOM = nil

TABS_MAPPING =
{
    ["SCENE_20SICHITAI2"] = "Termina", -- Southern Swamp (Clear)
    ["SCENE_KAKUSIANA"] = "Termina", -- Lone Peak Shrine & Grottos
    ["SCENE_SPOT00"] = "Termina", -- Cutscene Scene
    ["SCENE_WITCH_SHOP"] = "Termina", -- Magic Hags' Potion Shop
    ["SCENE_LAST_BS"] = "Moon", -- Majora's Lair
    ["SCENE_HAKASHITA"] = "Termine", -- Beneath the Graveyard
    ["SCENE_AYASHIISHOP"] = "Clock Town", -- Curiosity Shop
    ["SCENE_OMOYA"] = "Termina", -- Mama's House (Ranch House in PAL) & Barn
    ["SCENE_BOWLING"] = "Termina", -- Honey & Darling's Shop
    ["SCENE_SONCHONOIE"] = "Clock Town", -- The Mayor's Residence
    ["SCENE_IKANA"] = "Termina", -- Ikana Canyon
    ["SCENE_KAIZOKU"] = "Pirates' Fortress", -- Pirates' Fortress
    ["SCENE_MILK_BAR"] = "Clock Town", -- Milk Bar
    ["SCENE_INISIE_N"] = "Stone Tower Temple", -- Stone Tower Temple
    ["SCENE_TAKARAYA"] = "Clock Town", -- Treasure Chest Shop
    ["SCENE_INISIE_R"] = "Stone Tower Temple", -- Inverted Stone Tower Temple
    ["SCENE_OKUJOU"] = "Clock Town", -- Clock Tower Rooftop
    ["SCENE_OPENINGDAN"] = "Clock Town", -- Before Clock Town
    ["SCENE_MITURIN"] = "Woodfall Temple", -- Woodfall Temple
    ["SCENE_13HUBUKINOMITI"] = "Termina", -- Path to Mountain Village
    ["SCENE_CASTLE"] = "Ikana Castle", -- Ancient Castle of Ikana
    ["SCENE_DEKUTES"] = "Clock Town", -- Deku Scrub Playground
    ["SCENE_MITURIN_BS"] = "Woodfall Temple", -- Odolwa's Lair
    ["SCENE_SYATEKI_MIZU"] = "Clock Town", -- Town Shooting Gallery
    ["SCENE_HAKUGIN"] = "Snowhead Temple", -- Snowhead Temple
    ["SCENE_ROMANYMAE"] = "Termina", -- Milk Road
    ["SCENE_PIRATE"] = "Pirates' Fortress", -- Pirates' Fortress Interior
    ["SCENE_SYATEKI_MORI"] = "Termina", -- Swamp Shooting Gallery
    ["SCENE_SINKAI"] = "Termina", -- Pinnacle Rock
    ["SCENE_YOUSEI_IZUMI"] = "Termina", -- Fairy's Fountain
    ["SCENE_KINSTA1"] = "Swamp Spider House", -- Swamp Spider House
    ["SCENE_KINDAN2"] = "Ocean Spider House", -- Oceanside Spider House
    ["SCENE_TENMON_DAI"] = "Clock Town", -- Astral Observatory
    ["SCENE_LAST_DEKU"] = "Moon", -- Moon Deku Trial
    ["SCENE_22DEKUCITY"] = "Termina", -- Deku Palace
    ["SCENE_KAJIYA"] = "Termina", -- Mountain Smithy
    ["SCENE_00KEIKOKU"] = "Termina Field", -- Termina Field
    ["SCENE_POSTHOUSE"] = "Clock Town", -- Post Office
    ["SCENE_LABO"] = "Termina", -- Marine Research Lab
    ["SCENE_DANPEI2TEST"] = "Termina", -- Beneath the Graveyard (Day 3) and Dampe's House
    ["SCENE_16GORON_HOUSE"] = "Termina", -- Goron Shrine
    ["SCENE_33ZORACITY"] = "Zora Hall", -- Zora Hall
    ["SCENE_8ITEMSHOP"] = "Clock Town", -- Trading Post
    ["SCENE_F01"] = "Termina", -- Romani Ranch
    ["SCENE_INISIE_BS"] = "Stone Tower Temple", -- Twinmold's Lair
    ["SCENE_30GYOSON"] = "Termina", -- Great Bay Coast
    ["SCENE_31MISAKI"] = "Termina", -- Zora Cape
    ["SCENE_TAKARAKUJI"] = "Clock Town", -- Lottery Shop
    ["SCENE_TORIDE"] = "Pirates' Fortress", -- Pirates' Fortress Moat
    ["SCENE_FISHERMAN"] = "Termina", -- Fisherman's Hut
    ["SCENE_GORONSHOP"] = "Termina", -- Goron Shop
    ["SCENE_DEKU_KING"] = "Termina", -- Deku King's Chamber
    ["SCENE_LAST_GORON"] = "Moon", -- Moon Goron Trial
    ["SCENE_24KEMONOMITI"] = "Termina", -- Road to Southern Swamp
    ["SCENE_F01_B"] = "Termina", -- Doggy Racetrack
    ["SCENE_F01C"] = "Termina", -- Cucco Shack
    ["SCENE_BOTI"] = "Termina", -- Ikana Graveyard
    ["SCENE_HAKUGIN_BS"] = "Snowhead Temple", -- Goht's Lair
    ["SCENE_20SICHITAI"] = "Termina", -- Southern Swamp (poison)
    ["SCENE_21MITURINMAE"] = "Termina", -- Woodfall
    ["SCENE_LAST_ZORA"] = "Moon", -- Moon Zora Trial
    ["SCENE_11GORONNOSATO2"] = "Termina", -- Goron Village (spring)
    ["SCENE_SEA"] = "Great Bay Temple", -- Great Bay Temple
    ["SCENE_35TAKI"] = "Termina", -- Waterfall Rapids
    ["SCENE_REDEAD"] = "Beneath the Well", -- Beneath the Well
    ["SCENE_BANDROOM"] = "Zora Hall", -- Zora Hall Rooms
    ["SCENE_11GORONNOSATO"] = "Termina", -- Goron Village (winter)
    ["SCENE_GORON_HAKA"] = "Termina", -- Goron Graveyard
    ["SCENE_SECOM"] = "Termina", -- Sakon's Hideout
    ["SCENE_10YUKIYAMANOMURA"] = "Termina", -- Mountain Village (winter)
    ["SCENE_TOUGITES"] = "Termina", -- Ghost Hut
    ["SCENE_DANPEI"] = "Termina", -- Deku Shrine
    ["SCENE_IKANAMAE"] = "Termina", -- Road to Ikana
    ["SCENE_DOUJOU"] = "Clock Town", -- Swordsman's School
    ["SCENE_MUSICHOUSE"] = "Termina", -- Music Box House
    ["SCENE_IKNINSIDE"] = "Ikana Castle", -- Igos du Ikana's Lair
    ["SCENE_MAP_SHOP"] = "Termina", -- Tourist Information
    ["SCENE_F40"] = "Termina", -- Stone Tower
    ["SCENE_F41"] = "Termina", -- Inverted Stone Tower
    ["SCENE_10YUKIYAMANOMURA2"] = "Termina", -- Mountain Village (spring)
    ["SCENE_14YUKIDAMANOMITI"] = "Termina", -- Path to Snowhead
    ["SCENE_12HAKUGINMAE"] = "Termina", -- Snowhead
    ["SCENE_17SETUGEN"] = "Termina", -- Twin Islands (winter)
    ["SCENE_17SETUGEN2"] = "Termina", -- Twin Islands (spring)
    ["SCENE_SEA_BS"] = "Great Bay Temple", -- Gyorg's Lair
    ["SCENE_RANDOM"] = "Secret Shrine", -- Secret Shrine
    ["SCENE_YADOYA"] = "Clock Town", -- Stock Pot Inn
    ["SCENE_KONPEKI_ENT"] = "Termina", -- Great Bay Cutscene
    ["SCENE_INSIDETOWER"] = "Clock Town", -- Clock Tower Interior
    ["SCENE_26SARUNOMORI"] = "Woods of Mystery", -- Woods of Mystery
    ["SCENE_LOST_WOODS"] = "Termina", -- Lost Woods (Intro)
    ["SCENE_LAST_LINK"] = "Moon", -- Moon Link Trial
    ["SCENE_SOUGEN"] = "Moon", -- The Moon
    ["SCENE_BOMYA"] = "Clock Town", -- Bomb Shop
    ["SCENE_KYOJINNOMA"] = "Termina", -- Giant's Chamber
    ["SCENE_KOEPONARACE"] = "Termina", -- Gorman Track
    ["SCENE_GORONRACE"] = "Termina", -- Goron Racetrack
    ["SCENE_TOWN"] = "Clock Town", -- East Clock Town
    ["SCENE_ICHIBA"] = "Clock Town", -- West Clock Town
    ["SCENE_BACKTOWN"] = "Clock Town", -- North Clock Town
    ["SCENE_CLOCKTOWER"] = "Clock Town", -- South Clock Town
    ["SCENE_ALLEY"] = "Clock Town", -- Laundry Pool
}