CURRENT_ROOM = nil

TABS_MAPPING =
{
    ["0x00"] = "Termina", -- Southern Swamp (Clear)
    ["0x07"] = "Termina", -- Lone Peak Shrine & Grottos
    ["0x08"] = "Termina", -- Cutscene Scene
    ["0x0a"] = "Termina", -- Magic Hags' Potion Shop
    ["0x0b"] = "Moon", -- Majora's Lair
    ["0x0c"] = "Termina", -- Beneath the Graveyard
    ["0x0d"] = "Clock Town", -- Curiosity Shop
    ["0x10"] = "Termina", -- Mama's House (Ranch House in PAL) & Barn
    ["0x11"] = "Termina", -- Honey & Darling's Shop
    ["0x12"] = "Clock Town", -- The Mayor's Residence
    ["0x13"] = "Termina", -- Ikana Canyon
    ["0x14"] = "Pirates' Fortress", -- Pirates' Fortress
    ["0x15"] = "Clock Town", -- Milk Bar
    ["0x16"] = "Stone Tower Temple", -- Stone Tower Temple
    ["0x17"] = "Clock Town", -- Treasure Chest Shop
    ["0x18"] = "Stone Tower Temple", -- Inverted Stone Tower Temple
    ["0x19"] = "Clock Town", -- Clock Tower Rooftop
    ["0x1a"] = "Clock Town", -- Before Clock Town
    ["0x1b"] = "Woodfall Temple", -- Woodfall Temple
    ["0x1c"] = "Termina", -- Path to Mountain Village
    ["0x1d"] = "Ikana Castle", -- Ancient Castle of Ikana
    ["0x1e"] = "Clock Town", -- Deku Scrub Playground
    ["0x1f"] = "Woodfall Temple", -- Odolwa's Lair
    ["0x20"] = "Clock Town", -- Town Shooting Gallery
    ["0x21"] = "Snowhead Temple", -- Snowhead Temple
    ["0x22"] = "Termina", -- Milk Road
    ["0x23"] = "Pirates' Fortress", -- Pirates' Fortress Interior
    ["0x24"] = "Termina", -- Swamp Shooting Gallery
    ["0x25"] = "Termina", -- Pinnacle Rock
    ["0x26"] = "Termina", -- Fairy's Fountain
    ["0x27"] = "Swamp Spider House", -- Swamp Spider House
    ["0x28"] = "Ocean Spider House", -- Oceanside Spider House
    ["0x29"] = "Clock Town", -- Astral Observatory
    ["0x2a"] = "Moon", -- Moon Deku Trial
    ["0x2b"] = "Termina", -- Deku Palace
    ["0x2c"] = "Termina", -- Mountain Smithy
    ["0x2d"] = "Termina Field", -- Termina Field
    ["0x2e"] = "Clock Town", -- Post Office
    ["0x2f"] = "Termina", -- Marine Research Lab
    ["0x30"] = "Termina", -- Beneath the Graveyard (Day 3) and Dampe's House
    ["0x32"] = "Termina", -- Goron Shrine
    ["0x33"] = "Zora Hall", -- Zora Hall
    ["0x34"] = "Clock Town", -- Trading Post
    ["0x35"] = "Termina", -- Romani Ranch
    ["0x36"] = "Stone Tower Temple", -- Twinmold's Lair
    ["0x37"] = "Termina", -- Great Bay Coast
    ["0x38"] = "Termina", -- Zora Cape
    ["0x39"] = "Clock Town", -- Lottery Shop
    ["0x3b"] = "Pirates' Fortress", -- Pirates' Fortress Moat
    ["0x3c"] = "Termina", -- Fisherman's Hut
    ["0x3d"] = "Termina", -- Goron Shop
    ["0x3e"] = "Termina", -- Deku King's Chamber
    ["0x3f"] = "Moon", -- Moon Goron Trial
    ["0x40"] = "Termina", -- Road to Southern Swamp
    ["0x41"] = "Termina", -- Doggy Racetrack
    ["0x42"] = "Termina", -- Cucco Shack
    ["0x43"] = "Termina", -- Ikana Graveyard
    ["0x44"] = "Snowhead Temple", -- Goht's Lair
    ["0x45"] = "Termina", -- Southern Swamp (poison)
    ["0x46"] = "Termina", -- Woodfall
    ["0x47"] = "Moon", -- Moon Zora Trial
    ["0x48"] = "Termina", -- Goron Village (spring)
    ["0x49"] = "Great Bay Temple", -- Great Bay Temple
    ["0x4a"] = "Termina", -- Waterfall Rapids
    ["0x4b"] = "Beneath the Well", -- Beneath the Well
    ["0x4c"] = "Zora Hall", -- Zora Hall Rooms
    ["0x4d"] = "Termina", -- Goron Village (winter)
    ["0x4e"] = "Termina", -- Goron Graveyard
    ["0x4f"] = "Termina", -- Sakon's Hideout
    ["0x50"] = "Termina", -- Mountain Village (winter)
    ["0x51"] = "Termina", -- Ghost Hut
    ["0x52"] = "Termina", -- Deku Shrine
    ["0x53"] = "Termina", -- Road to Ikana
    ["0x54"] = "Clock Town", -- Swordsman's School
    ["0x55"] = "Termina", -- Music Box House
    ["0x56"] = "Ikana Castle", -- Igos du Ikana's Lair
    ["0x57"] = "Termina", -- Tourist Information
    ["0x58"] = "Termina", -- Stone Tower
    ["0x59"] = "Termina", -- Inverted Stone Tower
    ["0x5a"] = "Termina", -- Mountain Village (spring)
    ["0x5b"] = "Termina", -- Path to Snowhead
    ["0x5c"] = "Termina", -- Snowhead
    ["0x5d"] = "Termina", -- Twin Islands (winter)
    ["0x5e"] = "Termina", -- Twin Islands (spring)
    ["0x5f"] = "Great Bay Temple", -- Gyorg's Lair
    ["0x60"] = "Secret Shrine", -- Secret Shrine
    ["0x61"] = "Clock Town", -- Stock Pot Inn
    ["0x62"] = "Termina", -- Great Bay Cutscene
    ["0x63"] = "Clock Town", -- Clock Tower Interior
    ["0x64"] = "Woods of Mystery", -- Woods of Mystery
    ["0x65"] = "Termina", -- Lost Woods (Intro)
    ["0x66"] = "Moon", -- Moon Link Trial
    ["0x67"] = "Moon", -- The Moon
    ["0x68"] = "Clock Town", -- Bomb Shop
    ["0x69"] = "Termina", -- Giant's Chamber
    ["0x6a"] = "Termina", -- Gorman Track
    ["0x6b"] = "Termina", -- Goron Racetrack
    ["0x6c"] = "Clock Town", -- East Clock Town
    ["0x6d"] = "Clock Town", -- West Clock Town
    ["0x6e"] = "Clock Town", -- North Clock Town
    ["0x6f"] = "Clock Town", -- South Clock Town
    ["0x70"] = "Clock Town", -- Laundry Pool
}